services:
  edu-chatbot-llm:
    image: edu_ollama:latest
    build:
      context: ./ollama
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - llm-models:/root/.ollama
    environment:
      IS_PERSISTENT: "TRUE"
      OLLAMA_NO_CLOUD: "1"
      OLLAMA_KEEP_ALIVE: "-1" # Keeps the models loaded in memory. Prevents unloading after a timeout.
      OLLAMA_IGPU_ENABLE: "1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s

  edu-chatbot-llm-update:
    image: edu_ollama:latest
    build:
      context: ./ollama
      dockerfile: ./Dockerfile
    restart: "no"
    profiles:
      - update
    environment:
      OLLAMA_HOST: "http://edu-chatbot-llm:11434"
    volumes:
      - ./ollama/models.txt:/models.txt:ro
      - ./ollama/update_models.sh:/update_models.sh:ro
    entrypoint: ["/bin/bash", "/update_models.sh"]
    depends_on:
      edu-chatbot-llm:
        condition: service_healthy

  edu-chatbot-database:
    image: edu_chroma:latest
    build:
      context: ./chroma
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - database-core:/data
    environment:
      ANONYMIZED_TELEMETRY: "FALSE"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s

  edu-chatbot-database-update:
    build:
      context: ./edu_chatbot_ros2
      dockerfile: ./Dockerfile
    image: edu_chatbot_ros2:latest
    restart: "no"
    profiles:
      - update
    environment:
      - CHROMA_HOST=edu-chatbot-database
      - CHROMA_PORT=8000
      - OLLAMA_HOST=http://edu-chatbot-llm:11434
      - INGESTION_CACHE_PATH=/home/user/data
    volumes:
      - ./database:/home/user/database
      - database-cache:/home/user/data
    command: ["ros2", "run", "edu_chatbot_ros2", "database_update_node", "--ros-args", "-p", "wipe_database:=false", "--ros-args", "--log-level", "info"]
    depends_on:
      edu-chatbot-llm:
        condition: service_healthy
      edu-chatbot-database:
        condition: service_healthy

  edu-chatbot-node:
    build:
      context: ./edu_chatbot_ros2
      dockerfile: ./Dockerfile
    image: edu_chatbot_ros2:latest
    restart: unless-stopped
    profiles:
      - chatbot
    environment:
      - CHROMA_HOST=edu-chatbot-database
      - CHROMA_PORT=8000
      - OLLAMA_HOST=http://edu-chatbot-llm:11434
    command: ["ros2", "run", "edu_chatbot_ros2", "edu_chatbot_node", "--ros-args", "-p", "model:=llama3.2:3b", "-p", "top_k:=5", "--ros-args", "--log-level", "debug"]
    stdin_open: true
    tty: true
    depends_on:
      edu-chatbot-llm:
        condition: service_healthy
      edu-chatbot-database:
        condition: service_healthy

  edu-chatbot-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ports:
      - "3000:8080"
    profiles:
      - tools
    environment:
      WEBUI_AUTH: "FALSE"
      OLLAMA_BASE_URL: http://edu-chatbot-llm:11434
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      edu-chatbot-llm:
        condition: service_healthy

volumes:
  open-webui:
  llm-models:
  database-core:
  database-cache:
  
networks:
  default:
    name: edu_chatbot_network