# Audio capturer node parameters
/**:
  capturer_node:
    ros__parameters:
      device: 0
      format: 1
      channels: 1
      rate: 16000 # 48000
      chunk: 1280 # 80 ms chunks for best performance of openWakeWord
