services:
  edu_ros_base:
    build:
      target: base-cuda
      args:
        CUDA_VERSION: "13-2"

  edu-chatbot-llm:
    deploy: # Support for general Nvidia GPUS
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    runtime: nvidia # Special requirement for Nvidia Jetson

  edu-chatbot-wakeword:
    build:
      args:
        BASE_IMAGE: edu_ros_base:latest
    deploy: # Support for general Nvidia GPUS
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    runtime: nvidia # Special requirement for Nvidia Jetson

  edu-chatbot-stt:
    build:
      args:
        BASE_IMAGE: edu_ros_base:latest
        USE_CUDA: "1"
    deploy: # Support for general Nvidia GPUS
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    runtime: nvidia # Special requirement for Nvidia Jetson
