services:
  edu-chatbot-llm:
    deploy: # Support for general Nvidia GPUS
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    runtime: nvidia # Special requirement for Nvidia Jetson
